# Generated by Django 3.1.3 on 2020-12-31 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('file', models.ImageField(upload_to='product_photos')),
            ],
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(default='', null=True, verbose_name='상세설명')),
                ('address', models.CharField(max_length=140, verbose_name='주소')),
                ('time', models.DateField()),
            ],
            options={
                'verbose_name': '현장사례',
                'verbose_name_plural': '현장사례',
            },
            bases=('core.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.timestampedmodel',),
        ),
    ]
