# Generated by Django 3.1.3 on 2020-12-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20201211_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='special_item',
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(verbose_name='상세설명'),
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
