# Generated by Django 3.1.3 on 2020-12-17 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0003_auto_20201215_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '현장사례', 'verbose_name_plural': '현장사례'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(max_length=140, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='상세설명'),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='room',
            name='time',
            field=models.DateField(),
        ),
    ]
