# Generated by Django 3.1.3 on 2021-01-01 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jquestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jquestion',
            name='nickname',
            field=models.CharField(default=datetime.datetime(2021, 1, 1, 5, 41, 25, 902776, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
