# Generated by Django 3.1.3 on 2020-12-20 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooma',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.AddField(
            model_name='photo1',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='homes.rooma'),
        ),
    ]
