# Generated by Django 3.1.3 on 2021-01-01 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0002_auto_20201231_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jquestion',
            name='timestampedmodel_ptr',
        ),
        migrations.AlterField(
            model_name='rooma',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Jquestion',
        ),
    ]
