# Generated by Django 3.1.3 on 2020-12-17 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('homes', '0002_auto_20201215_1358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '문의사항', 'verbose_name_plural': '문의사항'},
        ),
        migrations.CreateModel(
            name='Rooma',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('name', models.CharField(max_length=100, verbose_name='제목')),
                ('address', models.CharField(max_length=140, verbose_name='주소')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homess', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
            ],
            options={
                'verbose_name': '메인화면 현장사례',
                'verbose_name_plural': '메인화면 현장사례',
            },
            bases=('core.timestampedmodel',),
        ),
    ]
