# Generated by Django 3.1.3 on 2020-12-17 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('homes', '0003_auto_20201218_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo1',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampedmodel')),
                ('files', models.ImageField(upload_to='product_photos1')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='homes.rooma')),
            ],
            bases=('core.timestampedmodel',),
        ),
    ]
