# Generated by Django 3.1.3 on 2020-12-17 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homes', '0004_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooma',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to=settings.AUTH_USER_MODEL, verbose_name='담당자'),
        ),
    ]
